import React from 'react'
import Head from 'next/head'
import Navbar from './Navbar'


export default function Layout({children, title }) {
  return (
    <div>
        <Head >

                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

        </Head>

        <Navbar/>
        <main>{children}</main>

    </div>
  )
}

Layout.defaultProps = {
    title : "page | next",

}