import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import dbConnect from '../../lib/dbtestConect'
// import ModelDoc from '../models/doc'
import ModelTest1 from '../../models/Test1'
import PostCrud from './[id]/PostCrud'
import { useRouter } from 'next/router'

export default function Home({ Test1 }) {
  const router = useRouter()

  const del = (id) => {
    try {
      fetch(`/api/test1/${id}`, { method: "DELETE" })
      router.push("/")
    } catch (error) {

      console.log(error)
    }

  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hello world</h1>
      <PostCrud />
      {Test1.map(({ title, content, _id }) => (
        <p key={_id}>

          {title} : {content} | -
          <Link href={`/${_id}`} >
            <button > view detail</button>
          </Link>
          | -
          <Link href={`/${_id}/EdictCrud `} >
            <button >Edit</button>
          </Link>

          <button onClick={() => del(_id)}>Delete</button>



        </p>
      ))}

    </div>
  )
}

export async function getServerSideProps() {

  await dbConnect()
  /* find all the data in our database */
  const result = await ModelTest1.find({}) // toma el model desde models

  // cambia el formato de _id
  const Test1 = result.map((doc) => {
    const Doc = doc.toObject()
    Doc._id = Doc._id.toString()
    return Doc //retornado para el map
  })
  console.log(result)

  return { props: { Test1: Test1 } }

}
